/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SegurancaRouteImport } from './routes/seguranca'
import { Route as RepararWindowsRouteImport } from './routes/reparar-windows'
import { Route as PrepararAmbienteRouteImport } from './routes/preparar-ambiente'
import { Route as PersonalizadoRouteImport } from './routes/personalizado'
import { Route as PerfisRouteImport } from './routes/perfis'
import { Route as OtimizarRouteImport } from './routes/otimizar'
import { Route as OtimizacoesRouteImport } from './routes/otimizacoes'
import { Route as ManutencaoProgramadaRouteImport } from './routes/manutencao-programada'
import { Route as LimpezaRouteImport } from './routes/limpeza'
import { Route as InicializacaoRouteImport } from './routes/inicializacao'
import { Route as DiagnosticoRouteImport } from './routes/diagnostico'
import { Route as DefenderRouteImport } from './routes/defender'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as CentralRouteImport } from './routes/central'
import { Route as AntiCheatRouteImport } from './routes/anti-cheat'
import { Route as IndexRouteImport } from './routes/index'

const SegurancaRoute = SegurancaRouteImport.update({
  id: '/seguranca',
  path: '/seguranca',
  getParentRoute: () => rootRouteImport,
} as any)
const RepararWindowsRoute = RepararWindowsRouteImport.update({
  id: '/reparar-windows',
  path: '/reparar-windows',
  getParentRoute: () => rootRouteImport,
} as any)
const PrepararAmbienteRoute = PrepararAmbienteRouteImport.update({
  id: '/preparar-ambiente',
  path: '/preparar-ambiente',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalizadoRoute = PersonalizadoRouteImport.update({
  id: '/personalizado',
  path: '/personalizado',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfisRoute = PerfisRouteImport.update({
  id: '/perfis',
  path: '/perfis',
  getParentRoute: () => rootRouteImport,
} as any)
const OtimizarRoute = OtimizarRouteImport.update({
  id: '/otimizar',
  path: '/otimizar',
  getParentRoute: () => rootRouteImport,
} as any)
const OtimizacoesRoute = OtimizacoesRouteImport.update({
  id: '/otimizacoes',
  path: '/otimizacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ManutencaoProgramadaRoute = ManutencaoProgramadaRouteImport.update({
  id: '/manutencao-programada',
  path: '/manutencao-programada',
  getParentRoute: () => rootRouteImport,
} as any)
const LimpezaRoute = LimpezaRouteImport.update({
  id: '/limpeza',
  path: '/limpeza',
  getParentRoute: () => rootRouteImport,
} as any)
const InicializacaoRoute = InicializacaoRouteImport.update({
  id: '/inicializacao',
  path: '/inicializacao',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticoRoute = DiagnosticoRouteImport.update({
  id: '/diagnostico',
  path: '/diagnostico',
  getParentRoute: () => rootRouteImport,
} as any)
const DefenderRoute = DefenderRouteImport.update({
  id: '/defender',
  path: '/defender',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CentralRoute = CentralRouteImport.update({
  id: '/central',
  path: '/central',
  getParentRoute: () => rootRouteImport,
} as any)
const AntiCheatRoute = AntiCheatRouteImport.update({
  id: '/anti-cheat',
  path: '/anti-cheat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anti-cheat': typeof AntiCheatRoute
  '/central': typeof CentralRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/defender': typeof DefenderRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/inicializacao': typeof InicializacaoRoute
  '/limpeza': typeof LimpezaRoute
  '/manutencao-programada': typeof ManutencaoProgramadaRoute
  '/otimizacoes': typeof OtimizacoesRoute
  '/otimizar': typeof OtimizarRoute
  '/perfis': typeof PerfisRoute
  '/personalizado': typeof PersonalizadoRoute
  '/preparar-ambiente': typeof PrepararAmbienteRoute
  '/reparar-windows': typeof RepararWindowsRoute
  '/seguranca': typeof SegurancaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anti-cheat': typeof AntiCheatRoute
  '/central': typeof CentralRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/defender': typeof DefenderRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/inicializacao': typeof InicializacaoRoute
  '/limpeza': typeof LimpezaRoute
  '/manutencao-programada': typeof ManutencaoProgramadaRoute
  '/otimizacoes': typeof OtimizacoesRoute
  '/otimizar': typeof OtimizarRoute
  '/perfis': typeof PerfisRoute
  '/personalizado': typeof PersonalizadoRoute
  '/preparar-ambiente': typeof PrepararAmbienteRoute
  '/reparar-windows': typeof RepararWindowsRoute
  '/seguranca': typeof SegurancaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anti-cheat': typeof AntiCheatRoute
  '/central': typeof CentralRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/defender': typeof DefenderRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/inicializacao': typeof InicializacaoRoute
  '/limpeza': typeof LimpezaRoute
  '/manutencao-programada': typeof ManutencaoProgramadaRoute
  '/otimizacoes': typeof OtimizacoesRoute
  '/otimizar': typeof OtimizarRoute
  '/perfis': typeof PerfisRoute
  '/personalizado': typeof PersonalizadoRoute
  '/preparar-ambiente': typeof PrepararAmbienteRoute
  '/reparar-windows': typeof RepararWindowsRoute
  '/seguranca': typeof SegurancaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anti-cheat'
    | '/central'
    | '/configuracoes'
    | '/defender'
    | '/diagnostico'
    | '/inicializacao'
    | '/limpeza'
    | '/manutencao-programada'
    | '/otimizacoes'
    | '/otimizar'
    | '/perfis'
    | '/personalizado'
    | '/preparar-ambiente'
    | '/reparar-windows'
    | '/seguranca'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anti-cheat'
    | '/central'
    | '/configuracoes'
    | '/defender'
    | '/diagnostico'
    | '/inicializacao'
    | '/limpeza'
    | '/manutencao-programada'
    | '/otimizacoes'
    | '/otimizar'
    | '/perfis'
    | '/personalizado'
    | '/preparar-ambiente'
    | '/reparar-windows'
    | '/seguranca'
  id:
    | '__root__'
    | '/'
    | '/anti-cheat'
    | '/central'
    | '/configuracoes'
    | '/defender'
    | '/diagnostico'
    | '/inicializacao'
    | '/limpeza'
    | '/manutencao-programada'
    | '/otimizacoes'
    | '/otimizar'
    | '/perfis'
    | '/personalizado'
    | '/preparar-ambiente'
    | '/reparar-windows'
    | '/seguranca'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AntiCheatRoute: typeof AntiCheatRoute
  CentralRoute: typeof CentralRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DefenderRoute: typeof DefenderRoute
  DiagnosticoRoute: typeof DiagnosticoRoute
  InicializacaoRoute: typeof InicializacaoRoute
  LimpezaRoute: typeof LimpezaRoute
  ManutencaoProgramadaRoute: typeof ManutencaoProgramadaRoute
  OtimizacoesRoute: typeof OtimizacoesRoute
  OtimizarRoute: typeof OtimizarRoute
  PerfisRoute: typeof PerfisRoute
  PersonalizadoRoute: typeof PersonalizadoRoute
  PrepararAmbienteRoute: typeof PrepararAmbienteRoute
  RepararWindowsRoute: typeof RepararWindowsRoute
  SegurancaRoute: typeof SegurancaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/seguranca': {
      id: '/seguranca'
      path: '/seguranca'
      fullPath: '/seguranca'
      preLoaderRoute: typeof SegurancaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reparar-windows': {
      id: '/reparar-windows'
      path: '/reparar-windows'
      fullPath: '/reparar-windows'
      preLoaderRoute: typeof RepararWindowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preparar-ambiente': {
      id: '/preparar-ambiente'
      path: '/preparar-ambiente'
      fullPath: '/preparar-ambiente'
      preLoaderRoute: typeof PrepararAmbienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personalizado': {
      id: '/personalizado'
      path: '/personalizado'
      fullPath: '/personalizado'
      preLoaderRoute: typeof PersonalizadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfis': {
      id: '/perfis'
      path: '/perfis'
      fullPath: '/perfis'
      preLoaderRoute: typeof PerfisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otimizar': {
      id: '/otimizar'
      path: '/otimizar'
      fullPath: '/otimizar'
      preLoaderRoute: typeof OtimizarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otimizacoes': {
      id: '/otimizacoes'
      path: '/otimizacoes'
      fullPath: '/otimizacoes'
      preLoaderRoute: typeof OtimizacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manutencao-programada': {
      id: '/manutencao-programada'
      path: '/manutencao-programada'
      fullPath: '/manutencao-programada'
      preLoaderRoute: typeof ManutencaoProgramadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/limpeza': {
      id: '/limpeza'
      path: '/limpeza'
      fullPath: '/limpeza'
      preLoaderRoute: typeof LimpezaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inicializacao': {
      id: '/inicializacao'
      path: '/inicializacao'
      fullPath: '/inicializacao'
      preLoaderRoute: typeof InicializacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostico': {
      id: '/diagnostico'
      path: '/diagnostico'
      fullPath: '/diagnostico'
      preLoaderRoute: typeof DiagnosticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/defender': {
      id: '/defender'
      path: '/defender'
      fullPath: '/defender'
      preLoaderRoute: typeof DefenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/central': {
      id: '/central'
      path: '/central'
      fullPath: '/central'
      preLoaderRoute: typeof CentralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anti-cheat': {
      id: '/anti-cheat'
      path: '/anti-cheat'
      fullPath: '/anti-cheat'
      preLoaderRoute: typeof AntiCheatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AntiCheatRoute: AntiCheatRoute,
  CentralRoute: CentralRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DefenderRoute: DefenderRoute,
  DiagnosticoRoute: DiagnosticoRoute,
  InicializacaoRoute: InicializacaoRoute,
  LimpezaRoute: LimpezaRoute,
  ManutencaoProgramadaRoute: ManutencaoProgramadaRoute,
  OtimizacoesRoute: OtimizacoesRoute,
  OtimizarRoute: OtimizarRoute,
  PerfisRoute: PerfisRoute,
  PersonalizadoRoute: PersonalizadoRoute,
  PrepararAmbienteRoute: PrepararAmbienteRoute,
  RepararWindowsRoute: RepararWindowsRoute,
  SegurancaRoute: SegurancaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
